version: '3.9'

services:
  testproject:
    image: testproject
    container_name: testapi
    ports:
      - "5050:80"
    build:
      context: .
      dockerfile: TestProject/Dockerfile
  webapi:
    image: webapiproject
    container_name: webapi
    ports:
      - "5051:80"
    build:
      context: .
      dockerfile: WebApplication/Dockerfile
